
SELECT * FROM PERFIL;

INSERT INTO PERFIL VALUES(1,'ADMINISTRADOR','Perfil con privilegios máximos');
INSERT INTO PERFIL VALUES(2,'PROFESIONAL','Perfil con privilegios intermedios');
INSERT INTO PERFIL VALUES(3,'USUARIO','Perfil con privilegios minimos');

--CONSULTAR LA TABLA
SELECT * FROM USUARIO;

--CREAR FK DE LA TABLA
ALTER TABLE USUARIO
ADD CONSTRAINT ID_PERFIL
FOREIGN KEY (ID_PERFIL)
REFERENCES PERFIL (ID_PERFIL);

INSERT INTO USUARIO VALUES (1,'Usuario_1','Clave_1',1);
INSERT INTO USUARIO VALUES (2,'Usuario_2','Clave_2',2);
INSERT INTO USUARIO VALUES (3,'Usuario_3','Clave_3',3);






SELECT * FROM RUBRO_EMPRESA;

INSERT INTO RUBRO_EMPRESA VALUES(1,'INDUSTRIAL','Empresas que emplean y transforman los recursos naturales (materias primas y fuentes de energía), para producir productos semielaborados que se emplearán para fabricar otros productos, o productos elaborados listos para el consumo.');
INSERT INTO RUBRO_EMPRESA VALUES(2,'MINERO','La minería es una actividad económica del sector primario representada por la explotación o extracción de los minerales que se han acumulado en el suelo y subsuelo en forma de yacimientos.');
INSERT INTO RUBRO_EMPRESA VALUES(3,'CONSTRUCCION','En los campos de la arquitectura e ingeniería, la construcción es el arte o técnica de fabricar edificios e infraestructuras');


SELECT * FROM EMPRESA;

--CREAR FK DE LA TABLA
ALTER TABLE EMPRESA
ADD CONSTRAINT ID_RUBRO_EMPRESA
FOREIGN KEY (ID_RUBRO_EMPRESA)
REFERENCES RUBRO_EMPRESA (ID_RUBRO_EMPRESA);

INSERT INTO EMPRESA VALUES (1,'THE COCA-COLA COMPANY','DESCRIPCION EMPRESA 01',1,700468003,1);
INSERT INTO EMPRESA VALUES (2,'WEBINAR CODELCO','DESCRIPCION EMPRESA 02',2,781996012,1);
INSERT INTO EMPRESA VALUES (3,'ACONCAGUA INMOBILIARIA','DESCRIPCION EMPRESA 03',3,718932457,1);








SELECT * FROM TIPO_SOLICITUD;

INSERT INTO TIPO_SOLICITUD VALUES(1,'SOLICITUD VISITA','CLIENTE SOLICITA LA VISITA DE UN PREVENCIONISTA EN TERRENO',SYSDATE);
INSERT INTO TIPO_SOLICITUD VALUES(2,'SOLICITUD CAPACITACION','CLIENTE SOLICITA CAPACITACIÓN DE TRABAJADORES EN TERRENO',SYSDATE);
INSERT INTO TIPO_SOLICITUD VALUES(3,'SOLICITUD ASESORIA','CLIENTE SOLICITA ASESORIA EN MATERIA DE LEGISLACION VIGENTE',SYSDATE);
INSERT INTO TIPO_SOLICITUD VALUES(4,'INFORMAR ACCIDENTE','CLIENTE SOLICITA ASESORIA EN MATERIA DE ACCIDENTES LABORALES',SYSDATE);

--CONSULTAR LA TABLA
SELECT * FROM SOLICITUD;

--CREAR FK DE LA TABLA
ALTER TABLE SOLICITUD
ADD CONSTRAINT ID_TIPO_SOLICITUD
FOREIGN KEY (ID_TIPO_SOLICITUD)
REFERENCES TIPO_SOLICITUD (ID_TIPO_SOLICITUD);

--CREAR FK DE LA TABLA
ALTER TABLE SOLICITUD
ADD CONSTRAINT ID_EMPRESA
FOREIGN KEY (ID_EMPRESA)
REFERENCES EMPRESA (ID_EMPRESA);


INSERT INTO SOLICITUD VALUES (1,SYSDATE,'SOLICITUD PRUEBA 01',1,1);
INSERT INTO SOLICITUD VALUES (2,SYSDATE,'SOLICITUD PRUEBA 02',2,2);
INSERT INTO SOLICITUD VALUES (3,SYSDATE,'SOLICITUD PRUEBA 03',3,3);



SELECT * FROM CONTRATO;

--CREAR FK DE LA TABLA
ALTER TABLE CONTRATO
ADD CONSTRAINT CONTRATO_ID_EMPRESA
FOREIGN KEY (ID_EMPRESA)
REFERENCES EMPRESA (ID_EMPRESA);

INSERT INTO CONTRATO VALUES(1,'CONTRATO PRUEBA 01',SYSDATE,1);
INSERT INTO CONTRATO VALUES(2,'CONTRATO PRUEBA 02',SYSDATE,2);
INSERT INTO CONTRATO VALUES(3,'CONTRATO PRUEBA 03',SYSDATE,3);


SELECT * FROM ACCIDENTE;

--CREAR FK DE LA TABLA
ALTER TABLE ACCIDENTE
ADD CONSTRAINT ID_ACCIDENTE
FOREIGN KEY (ID_EMPRESA)
REFERENCES EMPRESA (ID_EMPRESA);

INSERT INTO ACCIDENTE VALUES(1,SYSDATE,'ACCIDENTE 01',1);
INSERT INTO ACCIDENTE VALUES(2,SYSDATE,'ACCIDENTE 02',2);
INSERT INTO ACCIDENTE VALUES(3,SYSDATE,'ACCIDENTE 04',3);


SELECT * FROM PLANILLA_PAGO;

--CREAR FK DE LA TABLA
ALTER TABLE PLANILLA_PAGO
ADD CONSTRAINT PLANILLA_PAGO
FOREIGN KEY (ID_EMPRESA)
REFERENCES EMPRESA (ID_EMPRESA);

INSERT INTO PLANILLA_PAGO VALUES(1,8,2019,999999,1);
INSERT INTO PLANILLA_PAGO VALUES(2,8,2018,579324,2);
INSERT INTO PLANILLA_PAGO VALUES(3,12,2017,257913,3);


SELECT * FROM MULTAS;

--CREAR FK DE LA TABLA
ALTER TABLE MULTAS
ADD CONSTRAINT ID_MULTAS_ID_EMPRESA
FOREIGN KEY (ID_EMPRESA)
REFERENCES EMPRESA (ID_EMPRESA);

INSERT INTO MULTAS VALUES(1,'MULTA 01',SYSDATE,1);
INSERT INTO MULTAS VALUES(2,'MULTA 02',SYSDATE,2);
INSERT INTO MULTAS VALUES(3,'MULTA 03',SYSDATE,3);


SELECT * FROM PROFESIONAL;

INSERT INTO PROFESIONAL VALUES(1,'RAUL','PARDO','BAHAMUT',SYSDATE,1,16919995,7);
INSERT INTO PROFESIONAL VALUES(2,'CARLOS','ORTIZ','IFRIT',SYSDATE,1,18456782,6);
INSERT INTO PROFESIONAL VALUES(3,'OCTAVIO','MUÑOZ','SHIVA',SYSDATE,0,12281657,2);


SELECT * FROM DETALLE_VISITA;

INSERT INTO DETALLE_VISITA VALUES (1,'REVISIÓN DE DOCUMENTACIÓN','diseño, actualización y difución de sus documentos, cumpliendo todos los procesos legales.');
INSERT INTO DETALLE_VISITA VALUES (2,'CONDICIONES DE SEGURIDAD EN TERRENO','REVISIÓN DE LAS CONDICIONES LABORALES A LAS QUE ESTÁN EXPUESTOS LOS TRABAJADORES DE SU EMPRESA');
INSERT INTO DETALLE_VISITA VALUES (3,'INVESTIGACIÓN DE ACCIDENTES','Aviso a las autoridades, informes, revisión documental');


SELECT * FROM VISITA;

--CREAR FK DE LA TABLA
ALTER TABLE VISITA
ADD CONSTRAINT VISITA_EMPRESA
FOREIGN KEY (ID_EMPRESA)
REFERENCES EMPRESA (ID_EMPRESA);

ALTER TABLE VISITA
ADD CONSTRAINT VISITA_DETALLE_VISITA
FOREIGN KEY (ID_DETALLE_VISITA)
REFERENCES DETALLE_VISITA (ID_DETALLE_VISITA);

ALTER TABLE VISITA
ADD CONSTRAINT VISITA_PROFESIONAL
FOREIGN KEY (ID_PROFESIONAL)
REFERENCES PROFESIONAL (ID_PROFESIONAL);

INSERT INTO VISITA VALUES(1,SYSDATE,SYSDATE,0,1,1,1,1);
INSERT INTO VISITA VALUES(2,SYSDATE,SYSDATE,0,2,2,2,1);
INSERT INTO VISITA VALUES(3,SYSDATE,SYSDATE,0,3,3,3,1);


SELECT * FROM INFORME;

--CREAR FK DE LA TABLA
ALTER TABLE INFORME
ADD CONSTRAINT INFORME_VISITA
FOREIGN KEY (ID_VISITA)
REFERENCES VISITA (ID_VISITA);

INSERT INTO INFORME VALUES(1,SYSDATE,'RESULTADO INFORME 01',1);
INSERT INTO INFORME VALUES(2,SYSDATE,'RESULTADO INFORME 02',2);
INSERT INTO INFORME VALUES(3,SYSDATE,'RESULTADO INFORME 03',3);


SELECT * FROM ASISTENTES_CAPACITACION;

INSERT INTO ASISTENTES_CAPACITACION VALUES(1,16919995,'JOSE','COLLIO','FIGUEROA');
INSERT INTO ASISTENTES_CAPACITACION VALUES(1,16920000,'IGNACIO','GUTIERREZ','ROMERAL');
INSERT INTO ASISTENTES_CAPACITACION VALUES(1,16920004,'DIEGO','ZAPATA','HORMAZABAL');

INSERT INTO ASISTENTES_CAPACITACION VALUES(2,22715615,'CAMILA','SANCHEZ','ZOMOSA');
INSERT INTO ASISTENTES_CAPACITACION VALUES(2,22715622,'GERMAN','TORRES','SANDOVAL');
INSERT INTO ASISTENTES_CAPACITACION VALUES(2,22715620,'CLAUDIO','ANGULO','BRIONES');

INSERT INTO ASISTENTES_CAPACITACION VALUES(3,8614732,'MIRTHA','CASTRO','AMUNATEGUI');
INSERT INTO ASISTENTES_CAPACITACION VALUES(3,8614738,'SANDRA','DEL RIO','ORTUZAR');
INSERT INTO ASISTENTES_CAPACITACION VALUES(3,8614735,'FRANCISCO','SALAS','SILVA');

SELECT * FROM CAPACITACION;

--CREAR FK DE LA TABLA
ALTER TABLE CAPACITACION
ADD CONSTRAINT CAPACITACION_EMPRESA
FOREIGN KEY (ID_EMPRESA)
REFERENCES EMPRESA (ID_EMPRESA);

/* tengo que revisar como lo hago acá
ALTER TABLE CAPACITACION
ADD CONSTRAINT CAPACITACION_ASISTENTES
FOREIGN KEY (ID_ASISTENTES)
REFERENCES ASISTENTES_CAPACITACION (ID_ASISTENTES);
*/

ALTER TABLE CAPACITACION
ADD CONSTRAINT CAPACITACION_PROFESIONAL
FOREIGN KEY (ID_PROFESIONAL)
REFERENCES PROFESIONAL (ID_PROFESIONAL);

INSERT INTO CAPACITACION VALUES(1,SYSDATE,SYSDATE,0,1,1,1,1);
INSERT INTO CAPACITACION VALUES(2,SYSDATE,SYSDATE,0,2,2,2,1);
INSERT INTO CAPACITACION VALUES(3,SYSDATE,SYSDATE,0,3,3,3,1);


SELECT * FROM ASESORIA;

--CREAR FK DE LA TABLA
ALTER TABLE ASESORIA
ADD CONSTRAINT ASESORIA_EMPRESA
FOREIGN KEY (ID_EMPRESA)
REFERENCES EMPRESA (ID_EMPRESA);

ALTER TABLE ASESORIA
ADD CONSTRAINT ASESORIA_PROFESIONAL
FOREIGN KEY (ID_PROFESIONAL)
REFERENCES PROFESIONAL (ID_PROFESIONAL);

INSERT INTO ASESORIA VALUES(1,SYSDATE,SYSDATE,0,1,1,1);
INSERT INTO ASESORIA VALUES(2,SYSDATE,SYSDATE,0,2,2,1);
INSERT INTO ASESORIA VALUES(3,SYSDATE,SYSDATE,0,3,3,1);


SELECT * FROM LLAMADO;

--CREAR FK DE LA TABLA
ALTER TABLE LLAMADO
ADD CONSTRAINT LLAMADO_EMPRESA
FOREIGN KEY (ID_EMPRESA)
REFERENCES EMPRESA (ID_EMPRESA);

ALTER TABLE LLAMADO
ADD CONSTRAINT LLAMADO_PROFESIONAL
FOREIGN KEY (ID_PROFESIONAL)
REFERENCES PROFESIONAL (ID_PROFESIONAL);

INSERT INTO LLAMADO VALUES(1,SYSDATE,SYSDATE,'DESCRIPCION LLAMADO 01',0,1,1);
INSERT INTO LLAMADO VALUES(2,SYSDATE,SYSDATE,'DESCRIPCION LLAMADO 02',0,2,2);
INSERT INTO LLAMADO VALUES(3,SYSDATE,SYSDATE,'DESCRIPCION LLAMADO 03',0,3,3);







SELECT * FROM REPORTE;

--CREAR FK DE LA TABLA
ALTER TABLE REPORTE
ADD CONSTRAINT REPORTE_VISITA
FOREIGN KEY (ID_VISITA)
REFERENCES VISITA (ID_VISITA);

ALTER TABLE REPORTE
ADD CONSTRAINT REPORTE_CAPACITACION
FOREIGN KEY (ID_CAPACITACION)
REFERENCES CAPACITACION (ID_CAPACITACION);

ALTER TABLE REPORTE
ADD CONSTRAINT REPORTE_ASESORIA
FOREIGN KEY (ID_ASESORIA)
REFERENCES ASESORIA (ID_ASESORIA);

ALTER TABLE REPORTE
ADD CONSTRAINT REPORTE_LLAMADOS
FOREIGN KEY (ID_LLAMADO)
REFERENCES LLAMADO (ID_LLAMADO);

ALTER TABLE REPORTE
ADD CONSTRAINT REPORTE_ACCIDENTE
FOREIGN KEY (ID_ACCIDENTE)
REFERENCES ACCIDENTE (ID_ACCIDENTE);

ALTER TABLE REPORTE
ADD CONSTRAINT REPORTE_MULTA
FOREIGN KEY (ID_MULTA)
REFERENCES MULTAS (ID_MULTAS);

INSERT INTO REPORTE VALUES(1,'REPORTE 01',1,1,1,1,1,1);
INSERT INTO REPORTE VALUES(2,'REPORTE 02',2,2,2,2,2,2);
INSERT INTO REPORTE VALUES(3,'REPORTE 03',3,3,3,3,3,3);



SELECT * FROM FACTURA;

ALTER TABLE FACTURA
ADD CONSTRAINT PLANILLA_PAGO_FACTURA
FOREIGN KEY (ID_PLANILLA_PAGO)
REFERENCES PLANILLA_PAGO (ID_PLANILLA_PAGO);


INSERT INTO FACTURA VALUES (1,0,'DESCRIPCION FACTURA 01',SYSDATE,1);
INSERT INTO FACTURA VALUES (2,1,'DESCRIPCION FACTURA 02',SYSDATE,2);
INSERT INTO FACTURA VALUES (3,1,'DESCRIPCION FACTURA 04',SYSDATE,3);




SELECT * FROM PROFESIONAL;
SELECT * FROM CONTRATO_PROFESIONAL;

INSERT INTO CONTRATO_PROFESIONAL VALUES (1,SYSDATE,SYSDATE,1,1);
INSERT INTO CONTRATO_PROFESIONAL VALUES (2,SYSDATE,SYSDATE,1,2);
INSERT INTO CONTRATO_PROFESIONAL VALUES (3,SYSDATE,SYSDATE,1,3);

ALTER TABLE CONTRATO_PROFESIONAL
ADD CONSTRAINT CONTRPROFESIONAL_PROFESIONAL
FOREIGN KEY (ID_PROFESIONAL)
REFERENCES PROFESIONAL (ID_PROFESIONAL);




--JOIN PRUEBA
SELECT * FROM REPORTE;
SELECT * FROM CAPACITACION;
SELECT * FROM EMPRESA;

SELECT COUNT(C.ID_EMPRESA) "N° CAPACITACIONES: ", R.ID_REPORTE , R.DESCRIPCION ,
TO_CHAR(C.FECHA_INICIO,'YYYY/DD') "FECHA INCIO", 
TO_CHAR(C.FECHA_TERMINO,'YYYY') "FECHA TERMINO", 
E.NOMBRE , E.RUT_EMPRESA ||'-'|| E.DIGITO_VERIFICADOR "RUT_COMPLETO"
FROM REPORTE R JOIN CAPACITACION C
ON(R.ID_CAPACITACION = C.ID_CAPACITACION)
JOIN EMPRESA E
ON(C.ID_EMPRESA = E.ID_EMPRESA)
WHERE C.ID_EMPRESA = 3
GROUP BY R.ID_REPORTE , R.DESCRIPCION , C.FECHA_INICIO , C.FECHA_TERMINO , E.NOMBRE , E.RUT_EMPRESA , E.DIGITO_VERIFICADOR;




--PRUEBA PROCEDIMIENTOS. (SEGUIR TRABAJANDO ACÁ)
SET SERVEROUTPUT ON;
CREATE OR REPLACE PROCEDURE SP_VALIDAR_MOROSIDAD 
(RUT_EMPRESA_NUEVO IN EMPRESA.RUT_EMPRESA%TYPE,
RUT_EMPRESA_ANTIGUO IN EMPRESA.RUT_EMPRESA%TYPE ) 
IS
BEGIN
    UPDATE EMPRESA
    SET RUT_EMPRESA = RUT_EMPRESA_NUEVO
    WHERE RUT_EMPRESA = RUT_EMPRESA_ANTIGUO;
END SP_VALIDAR_MOROSIDAD;

--LLamando al procedimiento.
exec SP_VALIDAR_MOROSIDAD(71046800,70046800);

SELECT * FROM EMPRESA;





SELECT * FROM EMPRESA;

--CONSULTA PARA ACTUALIZAR UN REGISTRO.
UPDATE PROFESIONAL
SET RUT_EMPRESA = 71893245 
, DIGITO_VERIFICADOR = 7
WHERE ID_EMPRESA = 3;


--VACIAR LA TABLA 
DELETE FROM USUARIO;
